name: "Build"

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: ./ctm
    steps:
      - uses: actions/checkout@v6.0.2
      - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6
        with:
          python-version: '3.14'
      - uses: olafurpg/setup-scala@32ffa16635ff8f19cc21ea253a987f0fdf29844c # v14
        with:
          java-version: adopt@1.11
      - name: Build
        run: |
          chmod +x ./gradlew
          ./gradlew test --tests "it.unibo.big.localTests.*" --stacktrace --scan
          ./gradlew shadowJar
      - name: Run python
        run: |
          cd src/main/python/CTM
          pip install -r requirements.txt
          jupyter nbconvert --execute --to notebook --inplace charts.ipynb
          jupyter nbconvert --execute --to notebook --inplace PFPGrowth.ipynb
      - name: Release
        run: |
          npm install
          npx semantic-release
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
